Pass a `URI` object to `Net::HTTP.get_response`
Before, we were passing an `Addressable::URI` object when fetching
the response. This works, `Addresable::URI` behaving much like a `URI`
object.

However, the resulting URI’s `path` is returned as an `Addressable::URI`
object, which, due to a recent change in the OpenTelemetry’s
`Net::HTTP` patch is expected to be a string, resulting in the
following error:

```
NoMethodError

undefined method 'split' for an instance of Addressable::URI (NoMethodError)

                path_and_query = path.split('?')
```

We get around this by converting the uri object into a plain old `URI`
when making the request. This should ensure the telemetry middleware
can handle the URI correctly.