Raise descriptive error when nested_field called on non-nesting field
Add Schema::Field::NestedFieldNotSupportedError to provide a clear error
message when nested_field is called on a field that doesn't support nesting
(i.e., fields with type other than 'object' or 'array' of objects).

The error message includes:

- the field name
- the field type
- the nested field name being looked up
- explanation of which types support nesting
- the full picture of schema properties to aid debugging

This replaces the opaque NoMethodError: undefined method 'find' for nil
that previously occurred when nested_fields returned nil.