Handle TransitionError gracefully in WorkflowCompletion
Previously we've been rescuing `Transitions::InvalidTransition` and
displaying the error details in a flash message such as:

> Error: we can not change the status of this edition.
> Can't fire event `ready_for_factcheck` in current state `awaiting_factcheck`
> for `Edition` with ID 198

Actually it makes more sense to:

- show a generic error message to the user, rather than displaying
  technical details which won't be meaningful or helpful

- record the error at Sentry via `GovukError.notify` so that we can
  investigate and remove the pathway to this invalid action