Don’t load test tasks in production
When building the container in production (i.e when building the app
for deployment), we get the error:

```
LoadError: cannot load such file -- cucumber/rake/task (LoadError)
```

This wraps our test-related Rakefile stuff inside an
`Rails.env.production?` check so we only load the test rake tasks in
non-prod environments.